apiVersion: v1
kind: Service
metadata:
  name: marknamespace-webhook
  namespace: marknamespace-webhook
spec:
  selector:
    app: marknamespace-webhook
  ports:
    - port: 443
      targetPort: tls-alt
      name: application
