---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "marknamespace-webhook"
webhooks:
  - name: "marknamespace-webhook.danieldorado.github.io"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["namespaces"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "marknamespace-webhook"
        name: "marknamespace-webhook"
        path: "/mutating-namespace"
      caBundle: <CA-BUNDLE>
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
    # Limiting objects to send to the webhook by label
    # objectSelector:
    #   matchLabels:
    #     foo: bar
